// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ShopProjectTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test Logging
        /// </summary>
        public void LogIn()
        {
            #region Variable Declarations
            WinWindow uIHomePageShopProjectGWindow1 = this.UIHomePageShopProjectGWindow.UIHomePageShopProjectGWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UIHomePageShopProjectGWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Home Page - Shop Project - Google Chrome' window
            Mouse.Click(uIHomePageShopProjectGWindow1, new Point(1502, 100));

            // Click 'Home Page - Shop Project - Google Chrome' window
            Mouse.Click(uIHomePageShopProjectGWindow1, new Point(687, 273));

            // Type 'Control + a' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.LogInParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.Control);

            // Type 'admin{RShiftKey}@admin.pl' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.LogInParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Home Page - Shop Project - Google Chrome' window
            Mouse.Click(uIHomePageShopProjectGWindow1, new Point(657, 332));

            // Type 'Control + a' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.LogInParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.Control);

            // Type 'qw12{RShiftKey}QW!@' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.LogInParams.UIChromeLegacyWindowDocumentSendKeys3, ModifierKeys.None);

            // Move using Right button 'Home Page - Shop Project - Google Chrome' window
            Mouse.StartDragging(uIHomePageShopProjectGWindow1, new Point(604, 389), MouseButtons.Right, ModifierKeys.None);
            Mouse.StopDragging(uIHomePageShopProjectGWindow1, -20, 3);

            // Click 'Home Page - Shop Project - Google Chrome' window
            Mouse.Click(uIHomePageShopProjectGWindow1, new Point(551, 415));
        }
        
        #region Properties
        public virtual LogInParams LogInParams
        {
            get
            {
                if ((this.mLogInParams == null))
                {
                    this.mLogInParams = new LogInParams();
                }
                return this.mLogInParams;
            }
        }
        
        public UIHomePageShopProjectGWindow UIHomePageShopProjectGWindow
        {
            get
            {
                if ((this.mUIHomePageShopProjectGWindow == null))
                {
                    this.mUIHomePageShopProjectGWindow = new UIHomePageShopProjectGWindow();
                }
                return this.mUIHomePageShopProjectGWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInParams mLogInParams;
        
        private UIHomePageShopProjectGWindow mUIHomePageShopProjectGWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LogInParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Control + a' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "a";
        
        /// <summary>
        /// Type 'admin{RShiftKey}@admin.pl' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "admin{RShiftKey}@admin.pl";
        
        /// <summary>
        /// Type 'Control + a' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "a";
        
        /// <summary>
        /// Type 'qw12{RShiftKey}QW!@' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys3 = "qw12{RShiftKey}QW!@";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageShopProjectGWindow : WinWindow
    {
        
        public UIHomePageShopProjectGWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - Shop Project - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Home Page - Shop Project - Google Chrome");
            this.WindowTitles.Add("Log in - Shop Project - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UIHomePageShopProjectGWindow1
        {
            get
            {
                if ((this.mUIHomePageShopProjectGWindow1 == null))
                {
                    this.mUIHomePageShopProjectGWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIHomePageShopProjectGWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - Shop Project";
                    this.mUIHomePageShopProjectGWindow1.WindowTitles.Add("Home Page - Shop Project - Google Chrome");
                    this.mUIHomePageShopProjectGWindow1.WindowTitles.Add("Log in - Shop Project - Google Chrome");
                    #endregion
                }
                return this.mUIHomePageShopProjectGWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIHomePageShopProjectGWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1561641632";
            this.WindowTitles.Add("Log in - Shop Project - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Log in - Shop Project - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
